In [2]:
import numpy as np

In [4]:
arr2 = np.array([[1,2,3],[0,1,4],[5,6,0]])
print("arr2=%s"%arr2)

arr2=[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [6]:
#計算行列式
det = np.linalg.det(arr2)
#反轉矩陣
arr_inv = np.linalg.inv(arr2)

print("det(arr2)=%s"%det)
print("Inverse(arr2)=%s"%arr_inv)

det(arr2)=0.9999999999999987
Inverse(arr2)=[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
