In [2]:
import numpy as np

# Tips: numpy.arange(n): create random array range from 0 to n-1 
np_array = np.arange(10)

print("The np_array arange(10):%s"%np_array)
print(f"The np_array at index=4:{np_array[4]}")

np_array_copy = np_array.copy()
print("The np_array_copy from np_array.copy():%s"%np_array_copy)

# Tips: 切片 NumpyInstance[x1:x2] : 取 numpy array 第 1 維度第 x1 - (x2-1) 個元素的切片
print("The np_array slice from index(3 - 5): np_array[3:6]:%s"%np_array[3:6])

# Tips:可以用切片的方式同時把切片範圍的數值一次替換 NumpyInstance[x1:x2] = y, 將 numpy array 第 1 維度第 x1 - (x2-1) 個元素 替換為 y
np_array[3:6] = 32
print("The np_array is %s after replacing the index(3-5) elements by 32"%np_array)



The np_array arange(10):[0 1 2 3 4 5 6 7 8 9]
The np_array at index=4:4
The np_array_copy from np_array.copy():[0 1 2 3 4 5 6 7 8 9]
The np_array slice from index(3 - 5): np_array[3:6]:[3 4 5]
The np_array is [ 0  1  2 32 32 32  6  7  8  9] after replacing the index(3-5) elements by 32


In [3]:
## 2D Numpy Array ##
np_2d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D numpy array: %s"%np_2d_array)

# Tips: NumpyInstance.reshape(第1維元素數,第2維元素數,第3維元素數,....,最高維元素數)
#       將 Numpy Array 元素按指定維度重分配 然後生成新的陣列副本

np_array1 = np.arange(12) # new a 1D numpy array contains 12 elements

np_rshp_array1 = np_array1.reshape(2,2,3) # reshape to be a 2X2X3 3D Array
print("Reshape a 1D numpy array:\n\t %s\n to 3D(2X2X3):\n\t %s"%(np_array1, np_rshp_array1))

print("np_rshp_array1[0]:\n\t %s"%np_rshp_array1[0]) # [[0 1 2],[3 4 5]]
print("np_rshp_array1[1][1]:\n\t %s"%np_rshp_array1[1][1]) # [9 10 11]
print("np_rshp_array1[1][1][2]:\n\t %s"%np_rshp_array1[1][1][2]) # 11
    
## Multi Diadmons Numpy Array Slice ##
np_array2 = np.arange(36) #[0,1,2 .... , 35]
np_rshp_array2 = np_array2.reshape(6,6) #[[0 1 2 3 4 5],[6-11],[12-17],[18-23],[24-29],[30-35]]
print("np_rshp_array2:\n\t %s"%np_rshp_array2)
print("np_rshp_array2[0,2:4]:\n\t %s"%np_rshp_array2[0,2:4]) # 第 0 列 index(2-3) 元素 [2 3]
print("np_rshp_array2[:,3]:\n\t %s"%np_rshp_array2[:,3]) # 所有列(第1維)的 index=3 元素 [3 9 15 21 27 33]
print("np_rshp_array2[1:4,2:4]:\n\t %s"%np_rshp_array2[1:4,2:4]) # 所有1-3列(第1維) 的 index(2-3) 元素 [[8 9],[14 15],[20 21]]

# Tips: NumpyInstance[::n] : 設定取元素步長, 每 n 個元素取值 [start:end:step]
print("np_rshp_array2[::2,::2]:\n\t %s"%np_rshp_array2[::2,::2]) # 設置每一維度元素的步長來取值 # [[0 2 4],[12 14 16],[24 26 28]]

np_rshp_3d_array2 = np_array2.reshape(4,3,3)
"""[
       [[0 1 2],[3 4 5],[6 7 8]],
       [[9 10 11],[12 13 14],[15 16 17]],
       [[18 19 20],[21 22 23],[24 25 26]],
       [[27 28 29],[30 31 32],[33 34 35]]
   ]     
"""
print("np_rshp_3d_array2[2:,:1]:\n\t %s"%np_rshp_3d_array2[2:,:1]) # np_rshp_3d_array2[2:,:1] -> [ [[18 19 20]],[[27 28 29]] ]
np_rshp_3d_array2[2:,:1] = 22 #第一維的第index(2-last)元素, 第二維取index(0- 1-1)=index(0), 然後賦值 22
"""[
       [[0 1 2],[3 4 5],[6 7 8]],
       [[9 10 11],[12 13 14],[15 16 17]],
       [[18 19 20],[21 22 23],[24 25 26]],
       [[27 28 29],[30 31 32],[33 34 35]]
   ]     
"""
print("np_rshp_3d_array2 在部分元素賦值後:\n\t %s"%np_rshp_3d_array2)


2D numpy array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshape a 1D numpy array:
	 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 to 3D(2X2X3):
	 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
np_rshp_array1[0]:
	 [[0 1 2]
 [3 4 5]]
np_rshp_array1[1][1]:
	 [ 9 10 11]
np_rshp_array1[1][1][2]:
	 11
np_rshp_array2:
	 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
np_rshp_array2[0,2:4]:
	 [2 3]
np_rshp_array2[:,3]:
	 [ 3  9 15 21 27 33]
np_rshp_array2[1:4,2:4]:
	 [[ 8  9]
 [14 15]
 [20 21]]
np_rshp_array2[::2,::2]:
	 [[ 0  2  4]
 [12 14 16]
 [24 26 28]]
np_rshp_3d_array2[2:,:1]:
	 [[[18 19 20]]

 [[27 28 29]]]
np_rshp_3d_array2 在部分元素賦值後:
	 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[22 22 22]
  [21 22 23]
  [24 25 26]]

 [[22 22 22]
  [30 31 32]
  [33 34 35]]]


In [14]:
## Boolean 索引 ##
np_2d_array3 = (np.arange(36)).reshape(6,6)
print("np_2d_array3 =\n\t%s"%np_2d_array3)

x= np.array([0, 1, 2, 1, 4, 5])
# Tips: NumpyInstance 直接當變數與某個數值做邏輯比較, 即是將該 NumpyInstance 的每個元素與該數值做比較
#       結果會產生一個與 NumpyInstance 相通元素樹目的陣列, 每個元素是 True/False Boolean 值 由每個元素
#       與該數值比較而得到
y1 = x == 1 # y = array([False,  True, False,  True, False, False])
print("x == 1 array: %s"%y)

# Tips: 可以使用 boolean numpy array 來 filter 其他 numpy array 的元素
y2 = np_2d_array3[x==1] # np_2d_array3 的第1維所有索引位置對映到 x==1 boolean array 元素 為 true 的元素 才會被選中
                        # 此例 np_2d_array3[1] 和 np_2d_array3[3] 被選中, 因為 x==1 boolean array index (1,3) 為 true
print("np_2d_array3[x==1] = \n\t%s"%np_2d_array3[x==1])
print("np_2d_array3[x==1, 2:] = \n\t%s"%np_2d_array3[x==1,2:]) # 從 np_2d_array3[x==1] 中 取出 每一 1D元素 的 index(3,final)元素
                                                               # array[[8,9,10,11],[20,21,22,23]]
print("np_2d_array3[x==1, 2:] = \n\t%s"%np_2d_array3[x==1,-3:]) # 從 np_2d_array3[x==1] 中 取出 每一 1D元素 的 倒數第3個到最後一個元素
                                                                # array[[9,10,11],[21,22,23]]

# Tips: np.random.randn(m,n)產生一個符合常態分配的 m * n numpy array
np_normal_array4 = np.random.randn(4,4) # 產生 4*4 = 16 個 符合常態分配的元素 陣列
print("np_normal_array4 =\n\t%s"%np_normal_array4)

# 利用 boolean numpy array 方式 將 np_normal_array4 所有數值 大於 0 的元素指定為 10
np_normal_array4[np_normal_array4>0] = 10
print("np_normal_array4 after adjusting positive elements to 10: \n\t%s"%np_normal_array4)

np_2d_array3 =
	[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
x == 1 array: [False  True False  True False False]
np_2d_array3[x==1] = 
	[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]
np_2d_array3[x==1, 2:] = 
	[[ 8  9 10 11]
 [20 21 22 23]]
np_2d_array3[x==1, 2:] = 
	[[ 9 10 11]
 [21 22 23]]
np_normal_array4 =
	[[-0.26417034  1.79434826  0.15505973  0.33671561]
 [-0.06543368  0.94189073  1.0889092   1.58606192]
 [-0.68035949  0.85001311  1.29804579 -0.98114508]
 [ 0.41665125 -1.14160648 -0.35304487  0.68150661]]
np_normal_array4 after adjusting positive elements to 10: 
	[[-0.26417034 10.         10.         10.        ]
 [-0.06543368 10.         10.         10.        ]
 [-0.68035949 10.         10.         -0.98114508]
 [10.         -1.14160648 -0.35304487 10.        ]]


In [24]:
## 花式索引 (Fancy Indexing) ##

#Tips: 利用傳入一個 1D 索引陣列 給 NumpyInstance 指示 按照該陣列的元素排列次序作為 NumpyInstance 依序要娶的元素之索引
#      Example: np_array=[[1 2 3],[4 5 6],[7 8 9],[10 11 12]]
#      fancy_array1 = np_array[[3,1]] (依序取索引 3 和 1 的元素) = [[10 11 12],[4 5 6]]
#      fancy_array2 = np_array[[0,2,1,3]] (依序取索引 (0,2,1,3) 的元素) = [[1 2 3],[7 8 9],[4 5 6],[10 11 12]] -> 等於重新排列元素
#      如果要取多維陣列的元素, 則有 n 維 就 傳入 n 個 1D 索引陣列. 然後每個索引陣列會組合相同索引位置的元素 形成多維陣列的任一元素位置, 就可取得散佈在多維陣列中不同元素
#      FancyArray = NumpyInstance[[x1,x2,x3],[y1,y2,y3],[z1,z2,z3]] = [NumpyInstance[x1,y1,z1], NumpyInstance[x2,y2,z2], NumpyInstance[x3,y3,z3]]
#      Example: np_array2 = [[1,2],[4,8],[14,19]]
#      fancy_array3 = np_array2[[1,2],[0,1]] = [np_array2[1,0],np_array2[2,1]] = [4,19]

#Tips: Numpy.empty((n1,n2,n3, ....)) 產生 empty mD array, 之後需要初始化給每一元素賦值
np_2d_array5 = np.empty((8,4)) # generate 8*4 empty array
np_2d_array5
for i in range(8):
    np_2d_array5[i] = i
print("np_2d_array5 =\n\t%s"%np_2d_array5)

print("fancy_array1 =\n\t%s"%np_2d_array5[[2,6,1,7]]) # fancy indexing 1: 按傳入陣列索引元素依序取值

np_2d_array5 =
	[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
fancy_array1 =
	[[2. 2. 2. 2.]
 [6. 6. 6. 6.]
 [1. 1. 1. 1.]
 [7. 7. 7. 7.]]
